---
PE1:
  hostname: "192.168.10.176"
  groups:
    - pe
  data:
    interfaces:
      - name: Ethernet0/0
        vrf: CUSTOMER_789
        ip: 10.0.11.1/24
    bgp:
      neighbors:
        - vrf_name: CUSTOMER_789
          remote_ip: 10.0.11.2
          remote_as: 789

PE2:
  hostname: "192.168.10.119"
  groups:
    - pe
  data:
    interfaces:
      - name: Ethernet0/0
        vrf: CUSTOMER_777
        ip: 10.0.22.1/24
    bgp:
      neighbors:
        - vrf_name: CUSTOMER_777
          remote_ip: 10.0.22.2
          remote_as: 777

PE3:
  hostname: "192.168.10.177"
  groups:
    - pe
  data:
    interfaces:
      - name: Ethernet0/0
        vrf: CUSTOMER_777
        ip: 10.0.33.1/24
    bgp:
      neighbors:
        - vrf_name: CUSTOMER_777
          remote_ip: 10.0.33.2
          remote_as: 777

PE4:
  hostname: "192.168.10.178"
  groups:
    - pe
  data:
    interfaces:
      - name: Ethernet0/0
        vrf: CUSTOMER_789
        ip: 10.0.44.1/24
    bgp:
      neighbors:
        - vrf_name: CUSTOMER_789
          remote_ip: 10.0.44.2
          remote_as: 789
